### ISSUE TITLE
Translation GUI into German language

### ISSUE THREAD

**Issue by dg9vh** [rogerclarkmelbourne/radioddity_gd-77_cps#13]
Hi,

am I right, that translation of the gui into another language would be possible by translating the corresponding xml-file in "Language"-folder? If so, I would start to translate it into German. One problem I have is to translate the chm-file because I have no experience how to decompile this and translate it :-)

73 de Kim
DG9VH

**Comment by rogerclarkmelbourne** [comment]
Kim

Yes. I think thats the case.

I just tried copying English.xml to German.xml and also changed

`	<Language Id="Eng" Text="English" />`

to

`	<Language Id=Ger" Text="German" />`

And German appears in the Language menu

(I know this file should probably called Deutsche ;-)


One thing to note, Not all text is externalized 
But I can change this

**Comment by dg9vh** [comment]
Ok, I forked it by myself and started translating it now. What are you using as IDE? Microsoft Visual Studio? Just for testing ist :)

**Comment by dg9vh** [comment]
Ah, I see, it's ok only to put the XML-File into the existing Language-folder :-) So I do not need to compile it again :-) Would be easier :-)

**Comment by rogerclarkmelbourne** [comment]
No need to compile, just run the exe 

If you want to compile you need Visual Studio. You can use Visual Studio Community Edition, I think it should work.

**Comment by rogerclarkmelbourne** [comment]
BTW.

Tell me if any text is not in the XML.

(I know my new message for upload and download is not in the XML. I need to add it  and update the code

**Comment by rogerclarkmelbourne** [comment]
Umm.

I just checked and even some things which are defined in the XML are not being loaded and used in the application :-(
Looks like I need to fix the XML loading ;-)

**Comment by dg9vh** [comment]
No problem at all... I just translate all I can translate and would commit it into my local fork. If I have a state reached near at finish-line, I would make a pull-request into your repository.

You can find actual state of translation in https://github.com/dg9vh/radioddity_gd-77_cps2.0.5

**Comment by rogerclarkmelbourne** [comment]
BTW. 
I will add 3 new keys to the english

```
    <Item Id="codePlugReadConfirm"  Text="Are you sure you want to read the codeplug from the GD-77?\nThis will overwrite the current codeplug." />
    <Item Id="codePlugWriteConfirm"  Text="Are you sure you want to write this codeplug to the GD-77?\nThis will overwrite codeplug currently in the GD-77" />
    <Item Id="pleaseConfirm"  Text="Please confirm" />
```

**Comment by dg9vh** [comment]
If you commit this changes to your github, I would locate this textes within the xml and add them to the corresponding position in the german one to keep it similar to the origin.

**Comment by dg9vh** [comment]
Now I already put the new keys into the german file, so here we are ready so far.

**Comment by rogerclarkmelbourne** [comment]
Thanks

I have merged your changes, and I will publish a new installer after I have fixed some local merge conflicts with the new key Colin has added

**Comment by rogerclarkmelbourne** [comment]
BTW.
I'm not sure what we should do about the help file (.chm)  I think there may be a way to decompile it back to HTML, but I have not investigated how to decompile a .chm file or how to recompile it back to .chm from HTML

I think perhaps rather than CHM which is a windows only file format, we should move these help messages to another XML file and use CDATA tags to embed HTML inside the XML

**Comment by dg9vh** [comment]
ok, fine best... may this could be a way to do it :-) I would take a look, if it is possible on an easy way to decompile and recompile meanwhile.

**Comment by rogerclarkmelbourne** [comment]
I just merged, but I think there is a bug in the CPS, because I selected German from the Language menu and nothing changed :-(

**Comment by rogerclarkmelbourne** [comment]
Sorry

My mistake
It is working

**Comment by dg9vh** [comment]
Hi, 
![image](https://user-images.githubusercontent.com/13950650/36504397-ad0b9164-1750-11e8-8011-2d93d2fe55d4.png)

As you can see, it is working :-)

**Comment by dg9vh** [comment]
What is not working is, that the CPS always starts in German after selecting it... it always starts in English...

**Comment by dg9vh** [comment]
Sorry, my fault, too - it was a file-system-permissions-problem for my user in the default-installation-path C:\Program Files (x86)\Radioddity CPS2.0.5 - Community Edition

After altering the rights to full access it could write the ini-file with the german entry in it.

**Comment by rogerclarkmelbourne** [comment]
OK
Its not good that the CPS needs write permission. The language setting should be saved to a registry key 

Can you raise this as a bug

**Comment by rogerclarkmelbourne** [comment]
BTW.
Whats the german translation for the new message that Colin added??

> Warning: Rx and Tx bands are different. Radio performance may be affected

**Comment by dg9vh** [comment]
Oh, those are not in actually. Are they included in the English one?

**Comment by rogerclarkmelbourne** [comment]
Its new

**Comment by dg9vh** [comment]
I see... I add it now and then get it into a pull-request

**Comment by rogerclarkmelbourne** [comment]
Just tell me the text

I will update my local copy and then make a new installer

**Comment by rogerclarkmelbourne** [comment]
no need for a PR

**Comment by dg9vh** [comment]
is done :-)

**Comment by rogerclarkmelbourne** [comment]
I've added
`      <Control Id="lblxband" Text="Warnung: Rx- und Tx-Bänder sind unterschiedlich. Die Funkleistung kann beeinträchtigt sein" />`

**Comment by rogerclarkmelbourne** [comment]
Ah OK

**Comment by dg9vh** [comment]
ok, i would cancel my PR

**Comment by rogerclarkmelbourne** [comment]
Yes. Please

I need to make one other change, as the text box for this text is too small, I will make it bigger

**Comment by rogerclarkmelbourne** [comment]
OK
All working now...

I've add to copy English.chm to make German.chm, otherwise the "help" window at the bottom displays an error message

So we either need to make a new CHM file for German, or we need to develop a new system for the help

**Comment by rogerclarkmelbourne** [comment]
If you pull and then also try the installer. Let me know if there are any problems.

BTW. Colin's change is to allow "Cross band" operation, and the new warning message appears if Tx and Rx frequency are not in the same band.

This is because the firmware in the radio does not correctly handle the output power settings (or possibly does not send the command to the AT1846S chip to change band when it transmits

But it does work OK.. Just with about 1/2 power

**Comment by rogerclarkmelbourne** [comment]
@dg9vh 

I'm adding 2 new items

      <MenuItem Id="tsmiMoveUp" Text="Move up" />
      <MenuItem Id="tsmiDownUp" Text="Move down" />  

Whats the german for these.

Its used to move the Zones up and down in the list (it may be used for other things like moving the channel order as well

**Comment by dg9vh** [comment]
Can't find them in the current English.xml - could you please pull the changes to the repo that I can locate the changes?

**Comment by rogerclarkmelbourne** [comment]
Its in the development branch

https://github.com/rogerclarkmelbourne/radioddity_gd-77_cps2.0.5/blob/development/Language/German.xml#L440-441

**Comment by rogerclarkmelbourne** [comment]
So that colin can test my changes I've made a development branch

I'm putting the latest untested things in there

Actually there is an installer in there with the new Move up, Move down feature

**Comment by dg9vh** [comment]
ok, I committed a pull request to the development-branch

**Comment by rogerclarkmelbourne** [comment]
Thanks

**Comment by dg9vh** [comment]
Is this message not in the XML?
![image](https://user-images.githubusercontent.com/13950650/36596267-5ea81cbc-18a5-11e8-9366-5cb1f5a443c9.png)

**Comment by rogerclarkmelbourne** [comment]
Sorry.
I did not have time to put it in the XML

I will do that today

**Comment by rogerclarkmelbourne** [comment]
I've now added this to the development branch

**Comment by rogerclarkmelbourne** [comment]
BTW. I'm adding a new feature to download contacts from ham-digital.org "last heard" database.

I've added some new text to the XML files for this, but the functionality is not finished yet, so not everything is loaded from the xml file, and I may still change some things

**Comment by dg9vh** [comment]
No problem. If you put them into the xml in development branch, give me a go to take the changes.

**Comment by rogerclarkmelbourne** [comment]
The new screen texts are here

https://github.com/rogerclarkmelbourne/radioddity_gd-77_cps2.0.5/blob/development/Language/German.xml#L714-L730

Al;so the agreement text is 

https://github.com/rogerclarkmelbourne/radioddity_gd-77_cps2.0.5/blob/development/Language/German.xml#L765

I have not totally completed the development of the Download contacts screen and it does not read all texts from the XML yet, but if you translate the texts I can always move them if I can't make them work in their current location

Specifically

https://github.com/rogerclarkmelbourne/radioddity_gd-77_cps2.0.5/blob/development/Language/German.xml#L722

Is not read from the XML at the moment, as I think I need to have a special function to read this

Also Colin g4eml suggested I need some other messages to indicate how many contacts are already in the codeplug, and how many can be imported

So I will probably need to add some more texts when I have finished the functionality

**Comment by rogerclarkmelbourne** [comment]
German version was also updated my DL2MF so I will close this
