### ISSUE TITLE
Tone.text

### ISSUE THREAD

**Issue by lxa520** [rogerclarkmelbourne/radioddity_gd-77_cps#44]
first line;
none delete，add by code in multi-language

**Comment by rogerclarkmelbourne** [comment]
OK.
There was another bug for None on TxTone and Admit criteria but I fixed this.

**Comment by rogerclarkmelbourne** [comment]
Are any of these bugs fixed in CPS 3.1.0 ?   As I have tried to decompile that, but it takes too much time, so I'll just modify 3.0.6 to make CPS 3.1.1 when its released.

**Comment by lxa520** [comment]
3.10 is fixed this bug

**Comment by rogerclarkmelbourne** [comment]
Ah,

I see.
This change is in CPS 3.1.0

Tone setting can not be None any more.

I will need to test if this is a problem for existing codeplugs

**Comment by rogerclarkmelbourne** [comment]
OK

**Comment by rogerclarkmelbourne** [comment]
I have not changed this in my CPS but I did fix the bug caused by setting Admin Critera not enough options.

**Comment by lxa520** [comment]
You mentioned the CTCSS BUG many times, 
How much do you fix the version of this BUG

**Comment by lxa520** [comment]
only the "tx tone" is not "none", the "admit criteria" have "ctcss/dcs" option. i dont konw the bug which you said, you can provide the version which you fixed it.

**Comment by rogerclarkmelbourne** [comment]
I will raise separate issue and explain

**Comment by rogerclarkmelbourne** [comment]
I made new issue for you

https://github.com/rogerclarkmelbourne/radioddity_gd-77_cps2.0.5/issues/48

You can see my fix. Its easy ;-)

**Comment by rogerclarkmelbourne** [comment]
Closed due to no response in more than 6 months
