### ISSUE TITLE
VFO Offset step 25K

### ISSUE THREAD

**Issue by evgs** [rogerclarkmelbourne/radioddity_gd-77_cps#52]
CPS has wrong offset step (scan step) in droplist: 20K. 
When 20K is selected in CPS the radio uses actual value 25K.
So correct label should be 25K. 

I think here is typo:
https://github.com/rogerclarkmelbourne/radioddity_gd-77_cps/blob/666310f13ddc52a80bee4f667bf3028b9c0b7d73/DMR/VfoForm.cs#L4031

**Comment by rogerclarkmelbourne** [comment]
Thanks
I'll double check and then fix if there is a problem

**Comment by rogerclarkmelbourne** [comment]
Should be fixed in this commit

https://github.com/rogerclarkmelbourne/radioddity_gd-77_cps/commit/beaa909d0f0ae657d8eda9c868682d9d1e8c001a
