### ISSUE TITLE
Frequency step

### ISSUE THREAD

**Issue by andershogberg** [rogerclarkmelbourne/radioddity_gd-77_cps#54]
It would be great if one could have analog channels with a frequency step of 6.25 kHz (and others), for instance to be able to program PMR channels.
For me it works on the radio, if I select a zone (doesn't matter which one) and press the right arrow button I come to a "VFO" like mode. If I then go into Menu - Set - Radio Cfg - Freq Step there is multiple options (2.5k, 5.0k, 6.25k, 10k, 12,5k, 25k, 30k, 50k,).
This leads me to believe that you should be able to use these steps when creating analog channels. What do you think?
Firmware version 3.1.1

**Comment by rogerclarkmelbourne** [comment]
Do you mean change the firmware or make a change to the CPS

**Comment by andershogberg** [comment]
My bad!
I must have done something wrong when programming my channels initially, and got confused by the step and spacing while troubleshooting.
The spacing for the PMR channels is 12,5K it's just that the frequency is "off" by 6,25K. I.e. the first analog PMR-446 channel is at 446.00625MHz, and the following channels are 12,5K steps up..
No need to change anyhing!! Thanks for a great program!!
