### ISSUE TITLE
What power levels.

### ISSUE THREAD

**Issue by forkoz** [rogerclarkmelbourne/radioddity_gd-77_cps#57]
Has anyone experimented with the power levels and a meter in the calibration data. I found in tests online that TX power was lacking compared to baofeng, especially in analog. From what I've gathered UV-5R and GD77 use the same final output transistors at least on 1 band.

Since the calibration data appears to hold the same stuff as test menu on MD380/2017, what is the hex equivalent of what power? 

I want more than paltry 3 watts on UHF.

**Comment by rogerclarkmelbourne** [comment]
There is no official documentation about the GD-77 calibration.

The calibration screen display is curacy of work done by Jason VK7ZJA.

I think I'll remove it, since its causing confusion.

**Comment by forkoz** [comment]
I'm just asking if anyone investigated the calibration values and what power level they correspond to. I know there is no official documentation but I don't have a power meter. Removing/hiding stuff isn't really fixing the problem, all you had to say is I don't know. Don't take opening issues and asking questions as an affront. I used this tracker to go straight to the source regarding GD77 modification.
