### ISSUE TITLE
version 3.1.8 firmware

### ISSUE THREAD

**Issue by manotroll** [rogerclarkmelbourne/radioddity_gd-77_cps#58]
I am using the GD77CPS31XCommunityEditionInstaller.exe program

when programming it says the list is empty
I use your mod for this translated into portuguese of brazil

**Comment by rogerclarkmelbourne** [comment]
Try making a new empty codeplug with just the default channels made by Radioddity and try uploading that.

Threre may be some incompatibility between your existing codeplug and this software

**Comment by manotroll** [comment]
plus I did the channel list for your program

**Comment by rogerclarkmelbourne** [comment]
Please use the official CPS if there is a problem with firmware 3.1.8 using my software
