### ISSUE TITLE
Bug string error when importing

### ISSUE THREAD

**Issue by riku2015** [rogerclarkmelbourne/radioddity_gd-77_cps#59]
when importing contacts i get string error if use "?" questionmark on contact name.
however if do on cps it works, this come only while importing cvs channels.

**Comment by rogerclarkmelbourne** [comment]
I've not changed the contacts import / export, I've only changed the Channels export / import

This is probably a bug in the original official CPS which I used as the basis for this version.

Please post an example of a line in the CSV which causes the error

**Comment by riku2015** [comment]
this is releated to channel import. :)
CH_DATA,Os Profile,Digital,"434,42500","434,42500",1,1,Os Profile?,1,9000,Suomi2,pori,Openspot-gen,None,None,Low,12.5,No,Normal,0,120,5,0,0,0,0,0,0,0,1,-80,0,0,0,0,22

also offtopic, when importing 2 times channel list it will fail(cannot add channel to zone), always need delete all channels(what will clear the scanlist and zonelists). need manually readd. also importing my channelfile for some reason the channel order is not same..  :D im just rewriting the codeplug and notice this.

**Comment by rogerclarkmelbourne** [comment]
OK.

I've recently changed the Channels export / import, so it looks like it has some bugs :-(

**Comment by riku2015** [comment]
should i open new issue to that offtopic thing?

**Comment by rogerclarkmelbourne** [comment]
Yes. Please

**Comment by rogerclarkmelbourne** [comment]
Looks like the changes to the channels export are not a good idea.

I'll reinstate the old functionality

**Comment by rogerclarkmelbourne** [comment]
I have removed the new features in commit d79f776f7a1b6b97fb9fad796b8f605035b188e9

Please download the latest installer, and install it to reinstate the original Channels export/import
