### ISSUE TITLE
import channels (update) will result failure

### ISSUE THREAD

**Issue by riku2015** [rogerclarkmelbourne/radioddity_gd-77_cps#60]
when importing two times channel list it will fail(cannot add channel to zone, duplicate entries?), always need delete(clear) all channels(what will also clear the scanlist and custom zonelists). 
Resulting need manually readd the custom channels to zone lists and rewrite the scanlist.

only importing channels cvs on empty channel list will work, updating will not. issue is updating channel list wont work.
reproduce this -> add channels with full 16ch on each zone. -> update channels will result "cannot add channel to zone"

**Comment by riku2015** [comment]
not a big problem :) i took the very known risk when doing this. this is all about help finding bugs :)
This feature about import/export channels is very handy to mass edit everything. there is also a alternative, called dmrconfig but it have less options. but using that a gd77 codeplug can upload to other radios aswell :)

**Comment by rogerclarkmelbourne** [comment]
Looks like the changes to the channels export are not a good idea.

I'll reinstate the old functionality

**Comment by rogerclarkmelbourne** [comment]
I have removed the new features in commit d79f776f7a1b6b97fb9fad796b8f605035b188e9
