### ISSUE TITLE
Virus alert

### ISSUE THREAD

**Issue by 3835** [rogerclarkmelbourne/radioddity_gd-77_cps#63]
My antivirus detects a threat in the RadioddityGD77CPS31XCommunityEditionInstaller.exe file

> Trojan:Win32/Spursint.F!cl

**Comment by rogerclarkmelbourne** [comment]
Please ready my blog. It does not contain a blog, it’s just that virus scanners now flag a lot of false positives.

However I recommend you build the code from source rather than using the installer
